### ISSUE TITLE
First attempt at running `deployments` branch

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-deployments#1]
First attempt to run deployment.

- Oddly, github.com remotes show up as `govready-docker` instead of `govready-deployments`.
- Had to figure out newest code was in `deployments` branch

```bash
$ /<somedir>/govready-docker (deployments) $ python3 run.py deploy
[-]Deployment Choices:
===================================
1. azure
2. onprem_simple
3. aws
4. onprem_distributed

Choice: 4
[-]Attempting to [deploy] using the [onprem_distributed] method
[x]Deployments require a configuration json that satisfies: [deployments/onprem_distributed/config-validator.json]
$ /<somedir>/govready-docker (deployments) $ python3 run.py deploy --config test.json 
[-]Deployment Choices:
===================================
1. azure
2. onprem_simple
3. aws
4. onprem_distributed

Choice: 4
[-]Attempting to [deploy] using the [onprem_distributed] method
[x]File does not exist: deployments/onprem_distributed/config-validator.json.  Each deployment type must have this file to validate required values for deployment.
$ /<somedir>/govready-docker (deployments) $ cat test.json 
{
  "SECRET_KEY": "2h1_4t$j4ln6k#7k6x+ym@w2x&nomgoxuuw+p82&3mq=c!pyw)",
  "ADDRESS": "localhost:8000",
  "ADMINS": [
    {"username": "username", "email":"first.last@example.com", "password": "REPLACEME"}
  ]
}
$ /<somedir>/govready-docker (deployments) $ sublime ./
$ /<somedir>/govready-docker (deployments) $ python3 run.py deploy --type onprem_simple --config test.json
[-]Attempting to [deploy] using the [onprem_simple] method
[*]Config missing optional field: MOUNT_FOLDER - Mount folder to put artifacts, logs, etc. - Current directory
[*]Config missing optional field: GIT_URL - GovReady-Q Github Repo - Defaults to https://github.com/GovReady/govready-q.git
[*]Config missing optional field: VERSION - GovReady-Q version/tag - Defaulting to latest release
[*]Config missing optional field: DATABASE_CONNECTION_STRING - Database connection string: <db_connector>://<name>:<password>@<host>:<port>/<db_name> - Will create a Postgres server in the docker-compose deployment for you.  It will not have snapshots.
[*]Config missing optional field: NGINX_CERT - Full file path to Nginx cert.pem - Defaults to self signed
[*]Config missing optional field: NGINX_KEY - Full file path to Nginx key.pem - Defaults to self signed
[*]Config missing optional field: MAILGUN_API_KEY - Mailgun is used to submit an incoming email from notifications.  - No default provided.
[*]Config missing optional field: EMAIL_HOST - Host of Email Server. - No default provided.
[*]Config missing optional field: EMAIL_PORT - Port of Email Server. - No default provided.
[*]Config missing optional field: EMAIL_USER - User for the Email Server. - No default provided.
[*]Config missing optional field: EMAIL_PW - Password for the User for of Email Server. - No default provided.
[*]Config missing optional field: EMAIL_DOMAIN - Domain of the Email Server. - No default provided.
[*]Executing command: git -c versionsort.suffix=- ls-remote --tags --sort=v:refname https://github.com/GovReady/govready-q.git
[*]Executing command: docker-compose -f docker-compose.yaml down --remove-orphans  --rmi all
WARNING: The BUILD_FILE_NGINX_CERT variable is not set. Defaulting to a blank string.
WARNING: The BUILD_FILE_NGINX_KEY variable is not set. Defaulting to a blank string.
Removing network onprem_simple_q_network
WARNING: Network onprem_simple_q_network not found.
Removing image postgres:13.2-alpine
WARNING: Image postgres:13.2-alpine not found.
Removing image onprem_simple_govready-q
WARNING: Image onprem_simple_govready-q not found.
Removing image onprem_simple_nginx
WARNING: Image onprem_simple_nginx not found.
Removing image onprem_simple_govready-q-email-notifications
WARNING: Image onprem_simple_govready-q-email-notifications not found.
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    run(args)
  File "run.py", line 32, in run
    deployment.run()
  File "/<somedir>/govready-docker/deployments/onprem_simple/deploy.py", line 41, in run
    self.docker_build_tmp_files_copy(self.TMP_BUILD_FILES)
  File "/<somedir>/govready-docker/build_utils/deployment.py", line 54, in docker_build_tmp_files_copy
    if not os.path.exists(file_path):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by gregelin** [comment]
Values pprint'ed of `self`:

```python
{'config': {'ADDRESS': 'localhost:8000',
            'ADMINS': [{'email': 'first.last@example.com',
                        'password': 'REPLACEME',
                        'username': 'username'}],
            'DATABASE_CONNECTION_STRING': 'postgres://postgres:PASSWORD@postgres:5432/govready_q',
            'DEBUG': 'false',
            'EMAIL_DOMAIN': None,
            'EMAIL_HOST': None,
            'EMAIL_PORT': None,
            'EMAIL_PW': None,
            'EMAIL_USER': None,
            'GIT_URL': 'https://github.com/GovReady/govready-q.git',
            'HEALTH_CHECK_GOVREADY_Q': 'http://localhost:8000',
            'HOST': 'localhost',
            'HTTPS': 'true',
            'MAILGUN_API_KEY': None,
            'MOUNT_FOLDER': '/codedata/code/govready-docker/volumes',
            'NGINX_CERT': None,
            'NGINX_KEY': None,
            'ROOT_DIR': '/codedata/code/govready-docker',
            'SECRET_KEY': '2h1_4t$j4ln6k#7k6x+ym@w2x&nomgoxuuw+p82&3mq=c!pyw)',
            'VERSION': 'v0.9.3.2'},
 'kill_captured': False,
 'options': {'action': 'deploy',
             'config': 'test.json',
             'type': 'onprem_simple'},
 'validation_config': [{'description': 'Django Secret',
                        'key': 'SECRET_KEY',
                        'required': True},
                       {'description': "GovReady-Q's public address as would "
                                       'be entered in a web browser. Set with '
                                       '--address HOST:PORT (PORT optional if '
                                       '443)',
                        'key': 'ADDRESS',
                        'required': True},
                       {'default-message': 'Will auto-create an admin, you '
                                           'need to find it in the logs '
                                           'docker-compose logs',
                        'description': 'Administrator accounts. Ex: '
                                       '[{"username": "username", '
                                       '"email":"first.last@example.com", '
                                       '"password": "REPLACEME"}]',
                        'key': 'ADMINS',
                        'required': False},
                       {'default-message': 'Current directory',
                        'description': 'Mount folder to put artifacts, logs, '
                                       'etc.',
                        'key': 'MOUNT_FOLDER',
                        'required': False},
                       {'default-message': 'Defaults to '
                                           'https://github.com/GovReady/govready-q.git',
                        'description': 'GovReady-Q Github Repo',
                        'key': 'GIT_URL',
                        'required': False},
                       {'default-message': 'Defaulting to latest release',
                        'description': 'GovReady-Q version/tag',
                        'key': 'VERSION',
                        'required': False},
                       {'default-message': 'Will create a Postgres server in '
                                           'the docker-compose deployment for '
                                           'you.  It will not have snapshots.',
                        'description': 'Database connection string: '
                                       '<db_connector>://<name>:<password>@<host>:<port>/<db_name>',
                        'key': 'DATABASE_CONNECTION_STRING',
                        'required': False},
                       {'default-message': 'Defaults to self signed',
                        'description': 'Full file path to Nginx cert.pem',
                        'key': 'NGINX_CERT',
                        'required': False},
                       {'default-message': 'Defaults to self signed',
                        'description': 'Full file path to Nginx key.pem',
                        'key': 'NGINX_KEY',
                        'required': False},
                       {'default-message': 'No default provided.',
                        'description': 'Mailgun is used to submit an incoming '
                                       'email from notifications. ',
                        'key': 'MAILGUN_API_KEY',
                        'required': False},
                       {'default-message': 'No default provided.',
                        'description': 'Host of Email Server.',
                        'key': 'EMAIL_HOST',
                        'required': False},
                       {'default-message': 'No default provided.',
                        'description': 'Port of Email Server.',
                        'key': 'EMAIL_PORT',
                        'required': False},
                       {'default-message': 'No default provided.',
                        'description': 'User for the Email Server.',
                        'key': 'EMAIL_USER',
                        'required': False},
                       {'default-message': 'No default provided.',
                        'description': 'Password for the User for of Email '
                                       'Server.',
                        'key': 'EMAIL_PW',
                        'required': False},
                       {'default-message': 'No default provided.',
                        'description': 'Domain of the Email Server.',
                        'key': 'EMAIL_DOMAIN',
                        'required': False}]}
                        ```

**Comment by gregelin** [comment]
Issue fixed.
