### ISSUE TITLE
SITE_HOST

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-deployments#6]
Receiving 500 error when starting a questionnaire.

Error reported in log:
```
021-04-30 11:08:00,722 siteapp.views level INFO {"user": {"id": 2, "username": "admin"}, "event": "project_list"}
2021-04-30 11:08:05,651 django.request level ERROR Internal Server Error: /tasks/6/speedy-ssp-basic-info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/govready-q/guidedmodules/views.py", line 168, in new_view_func
    "ADMIN_ROOT_URL": settings.SITE_ROOT_URL + "/admin",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Issue appears to be that `settings.SITE_ROOT_URL` value is `NONE` instead of a correct string value.

`settings.SITE_ROOT_URL` is set in the following code from `siteapp/settings.py`:

```
# Add a convenience setting "SITE_ROOT_URL" that stores the root URL of the website.
# Construct value from preferred "govready-url" environment parameter and temporarily
# support the deprecated "https" and "host" environment settings.
SITE_ROOT_URL = None
if (GOVREADY_URL.hostname and GOVREADY_URL.hostname != ""):
	SITE_ROOT_URL = "{}://{}".format(GOVREADY_URL.scheme, GOVREADY_URL.netloc)
	print("INFO: 'SITE_ROOT_URL' set to {} ".format(SITE_ROOT_URL))
elif "host" in environment and "https" in environment:
	SITE_ROOT_URL = "%s://%s" % (("http" if not environment["https"] else "https"), environment["host"])
	print("INFO: 'SITE_ROOT_URL' set to {} ".format(SITE_ROOT_URL))
else:
	print("CRITICAL: No parameters set to determine SITE_ROOT_URL.")
```

Deployment was built with following `configuration.json` file (redacted):

```
{
    "ADMINS": "",
    "BRANDING": "",
    "DATABASE_CONNECTION_STRING": "",
    "EMAIL_DOMAIN": "",
    "EMAIL_HOST": "",
    "EMAIL_PORT": "",
    "EMAIL_PW": "",
    "EMAIL_USER": "",
    "GIT_URL": "",
    "GR_IMG_GENERATOR": "",
    "GR_PDF_GENERATOR": "",
    "HOST_ADDRESS": "testdocker-xxxxxxxx.govready.com",
    "HOST_PORT_HTTPS": "443",
    "MAILGUN_API_KEY": "",
    "MOUNT_FOLDER": "",
    "NGINX_CERT": "",
    "NGINX_KEY": "",
    "PROXY_AUTHENTICATION_EMAIL_HEADER": "",
    "PROXY_AUTHENTICATION_USER_HEADER": "",
    "SECRET_KEY": "d(cn88l6vubr-zutr&3fsm!gudy68!j-8d4bja*r7%_$i=0dv-",
    "VERSION": "",
    "REMOVE_STACK_ON_FAIL": false
}
```

NOTE: This deployment previously exhibited issues with healthcheck although other pages are working.

**Comment by gregelin** [comment]
Closed by #7
